Checks: >
  modernize-*,
  readability-*,
  performance-*,
  bugprone-*,
  cppcoreguidelines-*,
  -modernize-use-trailing-return-type,
  -modernize-avoid-c-arrays

WarningsAsErrors: ''
HeaderFilterRegex: '.*'
FormatStyle:     file
CheckOptions:
  - key:             modernize-use-auto.MinTypeNameLength
    value:           '5'
