name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-and-test:
    name: Build and run unit tests (CMake preset: test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake libssl-dev libboost-all-dev

      - name: Configure (CMake Preset: test)
        run: cmake --preset test

      - name: Build run-tests target
        run: cmake --build build-test --target run-tests -- -k 0

      - name: Run tests
        working-directory: build-test
        run: ctest --output-on-failure

  style:
    name: Style check (clang-format)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format checks
        run: bash scripts/check-style.sh
