name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake libssl-dev libboost-all-dev

      - name: Configure main build
        run: cmake --preset dev

      - name: Build main app
        run: cmake --build --preset dev --target HFT

      - name: Configure tests
        run: cmake --preset test

      - name: Build tests
        run: cmake --build --preset test --target run-tests

      - name: Run tests
        run: ctest --preset run-tests


  style:
    name: Style check (clang-format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format checks
        run: bash scripts/check-style.sh
